server:
  port: 8080
  name: "Sistema HHZZE"

spring:
  config:
    activate:
      on-profile: dev
  data:
    auto-index-creation: true
    uri: mongodb://192.168.15.23:27017/academia-hhzze?retryWrites=true&w=majority



